### ISSUE TITLE
Clicking on download file throws error

### ISSUE THREAD

**Issue by rnsammeta** [topolik/FSRepo#8]
After mapping to the existing file system path, if we click on download file (any file other than images), through Documents and Media display portlet, is throwing an exception.

**Comment by topolik** [comment]
Hi sammeta78, please can you share the exception stacktrace?

Thank you!

-- tom

**Comment by rnsammeta** [comment]
Hi Tom,

There's not much of a stack trace but it gives me the following error when I click on the download button (with latest war).

The requested resource was not found. 

http://localhost:8083/documents/12882/12883/Weekly%20MashUp%20Stats.xls?version=1.0&t=1340729505440

With the old war (1.0) it downloads the file though, albeit it gives me the following exception stack trace when I click on the file or 'VIEW' icon, (both the wars are tested on Liferay 6.1)

Caused by: org.hibernate.HibernateException: No Hibernate Session bound to thread, and configuration does not allow creation of non-transactional one here
    at org.springframework.orm.hibernate3.SpringSessionContext.currentSession(SpringSessionContext.java:63)
    at org.hibernate.impl.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:687)
    at com.liferay.portal.dao.orm.hibernate.SessionFactoryImpl.openSession(SessionFactoryImpl.java:73)
    at com.liferay.portal.service.persistence.impl.BasePersistenceImpl.openSession(BasePersistenceImpl.java:181)
    at com.liferay.portal.service.persistence.RepositoryEntryPersistenceImpl.fetchByR_M(RepositoryEntryPersistenceImpl.java:1566)

-Ram

**Comment by topolik** [comment]
OK, I'm not sure but I think I already fixed it. 

Can you please try to build the war from github sources and try again?

Thank you.

-- tom

**Comment by rnsammeta** [comment]
Works fine. Thanks!
